services:
  api:
    build:
      context: ./organochart-api
    container_name: organochart-api
    ports:
      - "5000:5000"
    volumes:
      - ./organochart-api:/app
      - /app/node_modules
    env_file:
      - .env

  client:
    build:
      context: ./organochart-client
    container_name: organochart-client
    ports:
      - "3000:3000"
    volumes:
      - ./organochart-client:/app
      - /app/node_modules
    depends_on:
      - api
