# Use official Node image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Install production dependencies (optional but good practice for smaller images)
RUN npm install --production

# Copy the rest of the source code
COPY . .

# Build the Next.js app
RUN npm run build

# Expose the port the app will run on
EXPOSE 3000

# Start the application in production mode
CMD ["npm", "run", "start"]
